### ISSUE TITLE
Set permissions correctly

### ISSUE THREAD

**Issue by ComvationAG** [Cloudrexx/scripts#7]
Currently, the permissions are set to `chmod w+x && chown www-data` during `./cx env init` from inside the web container.

This leads to the following problems:
* does not allow the user to edit the files on the host
* permissions are reset on `git checkout` and `git pull`

The permissions should be set in a way that:
* GIT does not change them
* the user is owner of (or at least in the same group as) the files

**Comment by CloudrexxTeam** [comment]
1. This is not related to this repository as its related to ./cx which is part of cloudrexx/cloudrexx
2. This was fixed some time ago by setting the www-data user id to the host's user id
